const objectives = [
  { label: 'SCHOOL', title: 'Study mathematics', desc: 'Complete exercises 12–20 from the functions worksheet.', progress: 62, tone: 'orange', meta: '3 of 5 sessions completed' },
  { label: 'BODY', title: 'Move your body', desc: 'Walk for 20 minutes after school.', progress: 35, tone: 'blue', meta: '2 of 6 sessions completed' },
  { label: 'SELF', title: 'Sleep better', desc: 'Leave your phone away from your bed at 11pm.', progress: 80, tone: 'green', meta: '4 of 5 nights completed' }
];

const views = [...document.querySelectorAll('.view')];
function showView(name) { views.forEach(v => v.classList.toggle('active-view', v.id === `view-${name}`)); document.querySelectorAll('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.view === name)); window.scrollTo({ top: 0, behavior: 'smooth' }); }
document.querySelectorAll('[data-view]').forEach(el => el.addEventListener('click', () => showView(el.dataset.view)));
document.querySelectorAll('.moods button').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.moods button').forEach(b => b.classList.remove('selected')); button.classList.add('selected'); }));
document.getElementById('checkin-btn').addEventListener('click', e => { e.currentTarget.textContent = 'Check-in saved ✓'; e.currentTarget.classList.add('confirmed'); });
function renderObjectives() { document.getElementById('objective-board').innerHTML = objectives.map(o => `<article class="board-card"><div class="objective-icon ${o.tone}">◎</div><span class="tag ${o.tone}-tag">${o.label}</span><h3>${o.title}</h3><p>${o.desc}</p><div class="progress"><span style="width:${o.progress}%"></span></div><small>${o.meta}</small></article>`).join(''); }
renderObjectives();
document.getElementById('add-objective').addEventListener('click', () => { const title = prompt('What is the objective?'); if (!title) return; objectives.unshift({ label:'NEW', title, desc:'Defined by you, supported by Kai.', progress:0, tone:'green', meta:'Not started yet' }); renderObjectives(); });
document.getElementById('save-journal').addEventListener('click', () => { const text = document.getElementById('journal-text'); document.getElementById('journal-status').textContent = text.value.trim() ? 'Reflection saved on this device ✓' : 'Write something before saving.'; if (text.value.trim()) text.value = ''; });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('sw.js'));

const API = localStorage.getItem('bussola_api') || 'http://localhost:8000';
let session = JSON.parse(localStorage.getItem('bussola_session') || 'null');
document.querySelectorAll('.brand span:last-child').forEach(node => { node.textContent = 'RISE'; });
document.querySelector('#auth-screen h1').textContent = 'Rise above the noise.';
document.querySelector('#auth-screen > .auth-card > p').textContent = 'Build your direction with Kai.';
let deferredInstallPrompt = null;
window.addEventListener('beforeinstallprompt', event => { event.preventDefault(); deferredInstallPrompt = event; document.getElementById('install-pwa').hidden = false; });
window.addEventListener('appinstalled', () => { deferredInstallPrompt = null; document.getElementById('install-pwa').textContent = '✓ Aplicação instalada'; });
const authScreen = document.getElementById('auth-screen');
const appShell = document.getElementById('app-shell');
const onboardingScreen = document.getElementById('onboarding-screen');
async function api(path, options = {}) {
  const headers = {'Content-Type':'application/json', ...(options.headers || {})};
  if (session?.access_token) headers.Authorization = `Bearer ${session.access_token}`;
  const response = await fetch(`${API}${path}`, {...options, headers});
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || 'The operation could not be completed.');
  return data;
}
function setSession(data) { session = data; localStorage.setItem('bussola_session', JSON.stringify(data)); }
function enterApp(me) { authScreen.hidden = true; appShell.hidden = false; document.getElementById('profile-name').textContent = me.display_name || 'My profile'; document.querySelectorAll('.admin-only').forEach(el => el.hidden = !['organization_admin','platform_admin','researcher'].includes(me.role)); if (me.onboarding_status !== 'complete' && me.role === 'youth') onboardingScreen.hidden = false; if (me.role === 'youth') { requestNotificationPermission(); loadDueNotifications(); } }
async function startSession(data) { setSession(data); const me = await api('/me'); session.user = me; localStorage.setItem('bussola_session', JSON.stringify(session)); enterApp(me); if (['organization_admin','platform_admin','researcher'].includes(me.role)) loadAdmin(); }
document.getElementById('login-form').addEventListener('submit', async e => { e.preventDefault(); const error = document.getElementById('login-error'); error.textContent=''; try { await startSession(await api('/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('login-email').value,password:document.getElementById('login-password').value})})); } catch (err) { error.textContent = err.message; } });
document.getElementById('register-form').addEventListener('submit', async e => { e.preventDefault(); const f=e.currentTarget; try { await startSession(await api('/auth/register',{method:'POST',body:JSON.stringify({display_name:document.getElementById('register-name').value,email:document.getElementById('register-email').value,password:document.getElementById('register-password').value,tenant_name:document.getElementById('register-tenant').value || null})})); } catch(err) { document.getElementById('login-error').textContent=err.message; } });
document.getElementById('onboarding-form').addEventListener('submit', async e => { e.preventDefault(); const f=new FormData(e.currentTarget); try { await api('/me/onboarding',{method:'PATCH',body:JSON.stringify({preferred_name:f.get('preferred_name'),energy_areas:String(f.get('energy')||'').split(',').map(x=>x.trim()).filter(Boolean),current_difficulties:String(f.get('difficulty')||'').split(',').map(x=>x.trim()).filter(Boolean),challenge_intensity:f.get('challenge_intensity'),proactive_consent:f.has('proactive_consent'),research_consent:f.has('research_consent'),service_terms:f.has('terms'),youth_assent:f.has('terms')})}); onboardingScreen.hidden=true; } catch(err) { alert(err.message); } });
async function loadAdmin() { try { const data=await api('/admin/dashboard'); document.getElementById('admin-kpis').innerHTML=Object.entries(data.kpis).map(([key,val])=>`<div class="kpi"><strong>${val}${key.includes('rate')?'%':''}</strong><span>${key.replaceAll('_',' ')}</span></div>`).join(''); const users=await api('/admin/users'); document.getElementById('users-list').innerHTML=users.items.map(u=>`<div class="user-row"><strong>${u.display_name}</strong><span>${u.email}</span><span class="pill">${u.role}</span><span class="pill">${u.onboarding_status}</span></div>`).join('') || '<p class="muted">Ainda sem utilizadores.</p>'; } catch(err) { console.warn(err); } }
document.getElementById('invite-user').addEventListener('click', async () => { const email=prompt('Email do convidado'); if(!email) return; const role=prompt('Papel: guardian, youth ou researcher','guardian'); try { const result=await api('/auth/invites',{method:'POST',body:JSON.stringify({email,role})}); alert(`Convite criado. Token para enviar: ${result.invite_token}`); } catch(err){ alert(err.message); } });
document.getElementById('load-research').addEventListener('click', async () => { try { const [kpis,data]=await Promise.all([api('/v1/analytics/kpis'),api('/research/conversations?purpose=pilot-review')]); document.getElementById('research-kpis').innerHTML=Object.entries(kpis.kpis).map(([key,val])=>`<div class="kpi"><strong>${val}${key.includes('rate')?'%':''}</strong><span>${key.replaceAll('_',' ')}</span></div>`).join(''); document.getElementById('research-list').innerHTML=data.items.map(row=>`<div class="research-row"><small>${row.pseudonym} · ${row.risk_level} · ${new Date(row.created_at).toLocaleString('en-GB')}</small><div><strong>Youth:</strong> ${row.user_message}</div><em><strong>Kai:</strong> ${row.assistant_message}</em></div>`).join('') || '<p>No authorized conversations found.</p>'; } catch(err){ alert(err.message); } });
if (session?.access_token && session.user) { enterApp(session.user); }

async function requestNotificationPermission() { if (!('Notification' in window)) return; if (Notification.permission === 'default') await Notification.requestPermission(); }
document.getElementById('install-pwa').addEventListener('click', async () => { if (deferredInstallPrompt) { deferredInstallPrompt.prompt(); await deferredInstallPrompt.userChoice; deferredInstallPrompt = null; return; } alert('On iPhone: open Safari Share and choose “Add to Home Screen”. On Android: open the browser menu and choose “Install app”.'); });
document.getElementById('logout-button').addEventListener('click', async () => { try { if (session?.refresh_token) await api('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})}); } catch (_) {} localStorage.removeItem('bussola_session'); session=null; appShell.hidden=true; onboardingScreen.hidden=true; authScreen.hidden=false; document.getElementById('login-password').value=''; });
async function loadDueNotifications() { try { const result=await api('/v1/proactive/check'); const card=document.getElementById('notification-card'); if (!result.items.length) return; card.hidden=false; card.innerHTML=`<span class="eyebrow">TODAY'S ACCOUNTABILITY</span><h3>${result.items[0].title}</h3><p>${result.items[0].body}</p><div class="notification-actions"><button class="primary" id="notify-done">Reply now <span>→</span></button><button class="link-button" id="notify-push">Enable notifications</button></div>`; if ('Notification' in window && Notification.permission === 'granted') new Notification(result.items[0].title,{body:result.items[0].body,icon:'./icon.svg'}); document.getElementById('notify-push').addEventListener('click',requestNotificationPermission); document.getElementById('notify-done').addEventListener('click',()=>showView('coach')); } catch(err) { console.debug('proactive check unavailable',err); } }
async function loadToday() { try { const today=await api('/me/today'); const root=document.getElementById('today-cards'); root.hidden=false; root.innerHTML=`<article class="liquid-orientation"><span class="eyebrow">A TUA DIREÇÃO</span><div class="orbital-mark">✦</div><h2>${today.orientation.title}</h2><p>${today.orientation.body}</p><small>${today.orientation.reason}</small></article>${today.action ? `<article class="liquid-action"><div class="card-label"><span class="eyebrow">O PRÓXIMO PASSO</span><span class="soft-pill">${today.action.kind === 'mission' ? 'experiência' : 'compromisso'}</span></div><h3>${today.action.title}</h3><p>${today.action.body}</p><div class="action-proof"><span>PROVA</span>${today.action.proof}</div><button class="primary" id="today-action">Abrir com Kai <span>→</span></button></article>` : ''}<article class="liquid-reflection"><span class="eyebrow">PARA LEVARES CONTIGO</span><h3>${today.reflection.title}</h3><p>${today.reflection.body}</p><button class="quiet-button" data-view="journal">Registar aprendizagem</button></article>`; document.getElementById('today-action')?.addEventListener('click',()=>showView('coach')); root.querySelector('[data-view]')?.addEventListener('click',()=>showView('journal')); } catch(err) { console.debug('today unavailable',err); } }
